version: "3.8"

services:
  frontend:
    container_name: frontend
    build:
      context: ./frontend
    ports:
      - "3000:3000"
    depends_on:
      [user-service, matching-service]

  user-service:
    container_name: user-service
    build:
      context: ./user-service
    ports:
      - "8000:8000"
    depends_on:
      - nginx

  mongo:
    container_name: mongo
    image: mongo
    ports:
      - "27017:27017"
    volumes:
      - mongoVolume:\data\db

  matching-service:
    container_name: matching-service
    build:
      context: ./matching-service
    ports:
      - "8001:8001"
    depends_on:
      - nginx

  nginx:
    container_name: nginx
    build:
      context: ./nginx
    ports:
      - "8080:8080"
    restart: always

volumes:
  mongoVolume: